/* default-themes.js — generated by colors-mockup.html ("Default Themes Designer").
   The built-in (always registered, undeletable) default themes / Canvas presets.
   UI colors of each theme live in theme-colors.css; chart colors live here. */
window.App = window.App || {};
App.DefaultThemes = [
  {
    "id": "default-dark",
    "name": "Default Dark",
    "base": "dark",
    "canvas": {
      "gridHorzColor": "#161c27",
      "gridVertColor": "#161c27",
      "background": "#0a0e17",
      "crosshairColor": "#6b7686",
      "crosshairStyle": "solid",
      "priceLineColor": "#8b95a5",
      "textColor": "#8b95a5",
      "bodyUp": "#089981",
      "bodyDown": "#f23645",
      "borderUp": "#089981",
      "borderDown": "#f23645",
      "wickUp": "#089981",
      "wickDown": "#f23645",
      "gridHorzEnabled": false,
      "gridVertEnabled": false,
      "dailyBreakEnabled": true,
      "askColor": "#8b95a5",
      "dailyBreakColor": "#2c3342"
    }
  },
  {
    "id": "default-light",
    "name": "Default Light",
    "base": "light",
    "canvas": {
      "gridHorzColor": "#161c27",
      "gridVertColor": "#161c27",
      "background": "#f5f5f5",
      "crosshairColor": "#6b7686",
      "crosshairStyle": "solid",
      "priceLineColor": "#8b95a5",
      "textColor": "#8b95a5",
      "bodyUp": "#089981",
      "bodyDown": "#f23645",
      "borderUp": "#089981",
      "borderDown": "#f23645",
      "wickUp": "#089981",
      "wickDown": "#f23645",
      "gridHorzEnabled": false,
      "gridVertEnabled": false,
      "dailyBreakEnabled": true,
      "askColor": "#8b95a5",
      "dailyBreakColor": "#c7c7c7"
    }
  },
  {
    "id": "ivory-white",
    "name": "Lavender",
    "base": "light",
    "canvas": {
      "gridHorzColor": "#c5c5d8",
      "gridVertColor": "#c5c5d8",
      "background": "#f7f7fd",
      "crosshairColor": "#000000",
      "crosshairStyle": "solid",
      "priceLineColor": "#4318c0",
      "textColor": "#6a6998",
      "bodyUp": "#37e340",
      "bodyDown": "#ff4448",
      "borderUp": "#000000",
      "borderDown": "#000000",
      "wickUp": "#000000",
      "wickDown": "#000000",
      "gridHorzEnabled": false,
      "gridVertEnabled": false,
      "dailyBreakEnabled": true,
      "askColor": "#4318c0",
      "dailyBreakColor": "#c5c5d8"
    }
  }
];
